In [18]:
import matplotlib.pyplot as plt
import numpy as np

In [19]:
matA = np.array([[5, 3], [4, 2]])
matB = np.array([[1, 2], [3, 4]])
print(matA)
print()
print(matB)

[[5 3]
 [4 2]]

[[1 2]
 [3 4]]


In [20]:
matA_inv = np.linalg.inv(matA)
matB_inv = np.linalg.inv(matB)

print(matA_inv)
print()
print(matB_inv)

[[-1.   1.5]
 [ 2.  -2.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
(matA  @ matB) @ (matB_inv @ matA_inv)

array([[1.00000000e+00, 7.10542736e-15],
       [0.00000000e+00, 1.00000000e+00]])