In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
matA = np.array([[5, 3], [4, 2]])
matB = np.array([[1, 2], [3, 4]])
print(matA)
print()
print(matB)

[[5 3]
 [4 2]]

[[1 2]
 [3 4]]


In [3]:
matA_inv = np.linalg.inv(matA)
matB_inv = np.linalg.inv(matB)

print(matA_inv)
print()
print(matB_inv)

[[-1.   1.5]
 [ 2.  -2.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
result = (matA @ matB) @ (matA_inv @ matB_inv)
result = np.round(result, decimals=10)  
print(result)


[[-111.    47. ]
 [ -81.5   34.5]]


In [6]:
np.linalg.inv(matA.T)

array([[-1. ,  2. ],
       [ 1.5, -2.5]])

In [7]:
np.linalg.inv(matA).T

array([[-1. ,  2. ],
       [ 1.5, -2.5]])

In [1]:
import torch 
q = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
k = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
q@k.T

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

In [2]:
q

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [3]:
v = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
q@k.T@v

tensor([[123., 156.],
        [281., 356.],
        [439., 556.]])

In [25]:
import torch

q = torch.randint(1, 5, (3,2))  # Correct way
k = torch.randint(1, 5, (3,2))  # Correct way

print(q)
print(k)


tensor([[3, 3],
        [4, 3],
        [2, 2]])
tensor([[4, 1],
        [3, 4],
        [1, 1]])


In [28]:
(q @ k.T) @ q

tensor([[141, 120],
        [167, 143],
        [ 94,  80]])

In [5]:
import torch
torch.tensor([[-1, -1], [-1, -1]]) @ torch.tensor([[1], [1]])

tensor([[-2],
        [-2]])